import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { readTextIfExists } from './io'

/**
 * The published skill ledger (source root `skills.json`), generated by
 * `iforge publish` from the dev repo's meta/assets.json. It is not a
 * cross-repo schema contract like catalog/profiles, so it is parsed
 * structurally rather than ajv-validated.
 */
export interface SkillEntry {
  name: string
  source: 'custom' | 'mirror' | 'official'
  repo?: string
  path?: string
  commit?: string
  updated?: string
  refUrl?: string
  install?: string
}

export interface SkillRow {
  name: string
  source: SkillEntry['source']
  description: string
  install: string | null
  present: boolean // whether the source repo holds a directory for this skill
  repo?: string
  refUrl?: string
}

const IFIT_REPO = 'oNo500/ifit'

export function loadSkillsLedger(root: string): SkillEntry[] | null {
  const raw = readTextIfExists(join(root, 'skills.json'))
  if (raw === null) return null
  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch (error) {
    throw new Error(`skills.json: invalid JSON (${String(error)})`, { cause: error })
  }
  if (!Array.isArray(parsed)) throw new Error('skills.json: expected an array of skill entries')
  return parsed as SkillEntry[]
}

/**
 * The three install forms are fixed by SKILLS.md: custom and mirror skills are
 * distributed from this repo and install by name, official ones are not held
 * here at all and install straight from upstream. A hand-written `install`
 * field records a real-world provenance that no derived form captures, so it
 * wins whenever present.
 */
export function installCommandFor(entry: SkillEntry): string | null {
  if (entry.install !== undefined) return entry.install
  if (entry.source === 'official') {
    return entry.repo === undefined ? null : `pnpx skills add ${entry.repo} -s ${entry.name}`
  }
  return `pnpx skills add ${IFIT_REPO} -s ${entry.name}`
}

/**
 * Pulls the description out of a SKILL.md frontmatter block. Skill frontmatter
 * routinely wraps description across lines via a YAML block scalar (`>-`), so
 * continuation lines are folded back into one line for single-row display.
 */
export function descriptionFromSkillMd(content: string): string {
  const fence = /^---\n([\s\S]*?)\n---/u.exec(content)
  if (fence === null) return ''
  const lines = (fence[1] ?? '').split('\n')
  const startIndex = lines.findIndex((line) => line.startsWith('description:'))
  if (startIndex === -1) return ''

  const head = (/^description:[ \t]*(.*)$/u.exec(lines[startIndex] ?? '')?.[1] ?? '').trim()
  const continuation: string[] = []
  for (const line of lines.slice(startIndex + 1)) {
    // A new top-level key ends the value; only indented lines continue it.
    if (!/^[ \t]/u.test(line)) break
    const trimmed = line.trim()
    if (trimmed !== '') continuation.push(trimmed)
  }

  const isBlockScalar = head === '>-' || head === '>' || head === '|' || head === '|-'
  const parts = isBlockScalar ? continuation : [head, ...continuation]
  return parts.join(' ').trim()
}

function matchesGrep(row: { name: string; description: string }, grepLower: string): boolean {
  return row.name.toLowerCase().includes(grepLower) || row.description.toLowerCase().includes(grepLower)
}

/**
 * The ledger is an editing account and always sits at the raw source root,
 * while skill directories follow the artifact layout (staged under artifacts/
 * in a dev-repo checkout) -- hence the two separate bases.
 */
export function listSkills(root: string, opts?: { grep?: string; artifactBase?: string }): SkillRow[] {
  const ledger = loadSkillsLedger(root)
  if (ledger === null) return []

  const skillsBase = opts?.artifactBase ?? root
  const grepLower = opts?.grep?.toLowerCase()
  const rows: SkillRow[] = []
  for (const entry of [...ledger].toSorted((a, b) => a.name.localeCompare(b.name))) {
    const skillMd = join(skillsBase, 'skills', entry.name, 'SKILL.md')
    const present = existsSync(join(skillsBase, 'skills', entry.name))
    const content = readTextIfExists(skillMd)
    const row: SkillRow = {
      name: entry.name,
      source: entry.source,
      description: content === null ? '' : descriptionFromSkillMd(content),
      install: installCommandFor(entry),
      present,
      ...(entry.repo === undefined ? {} : { repo: entry.repo }),
      ...(entry.refUrl === undefined ? {} : { refUrl: entry.refUrl }),
    }
    if (grepLower !== undefined && !matchesGrep(row, grepLower)) continue
    rows.push(row)
  }
  return rows
}
